M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-15T10:18:16-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-15T10:18:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
%
G90
G05
T1
X5.6634Y-4.4291
T2
X4.876Y-4.4291
M30
