M48
; DRILL file {KiCad 9.0.0} date 2025-03-01T15:34:36-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-01T15:34:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
%
G90
G05
T1
X143.85Y-112.5
T2
X123.85Y-112.5
M30
